#!/bin/sh

set -eu

docker run --rm -it \
  --cap-drop ALL --security-opt=no-new-privileges \
  --read-only \
  -u 1000:1000 \
  --tmpfs=/home/appuser/.cache \
  -v "$HOME/apps/yt-dlp":/home/appuser/workdir \
  yt-dlp "$@"
