#!/usr/bin/env bash
set -euo pipefail

USER_ID=$(( 10000 + RANDOM % 10000 ))

if [ -t 1 ]; then
  IT='-it'
else
  IT='-i'
fi

docker run --rm "$IT" \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only \
  -u $USER_ID:$USER_ID \
  kasa "$@"
