#!/usr/bin/env bash

set -euo pipefail

COMMAND=$(basename $0)

if [[ -t 0 ]]; then
  IT='-it'
else
  IT='-i'
fi

if [[ -t 1 ]]; then
  PRETTY=all
else
  PRETTY=format
fi

docker run --rm "$IT" \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only \
  -u 4837:4837 \
  --entrypoint=$COMMAND \
  httpie --pretty "$PRETTY" "$@"
