#!/usr/bin/env bash
set -euo pipefail

USER_ID=$(( 10000 + RANDOM % 10000 ))

COMMAND=$(basename $0)

if [[ -t 0 ]]; then
  IT='-it'
else
  IT='-i'
fi

if [[ -t 1 ]]; then
  PRETTY=all
else
  PRETTY=format
fi

docker run --rm "$IT" \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only \
  -u $USER_ID:$USER_ID \
  --entrypoint=$COMMAND \
  httpie --pretty "$PRETTY" "$@"
