#!/bin/sh

set -eu

docker run --rm -it \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only --network=none \
  -u 1000:1000 \
  -v "$HOME/apps/kid3":/home/appuser/workdir \
  kid3-cli "$@"
