#!/bin/sh

docker run --rm --name=sox \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only --network=none \
  -u 1000:1000 \
  -v "$HOME/apps/sox":/home/appuser/workdir \
  sox:latest "$@"
