#!/bin/sh

docker run --rm --name=sox \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only --network=none \
  -u 1000:1000 \
  --mount type=bind,src="$(pwd)",dst=/home/appuser/workdir \
  sox:latest "$@"
