#!/bin/sh

set -eu

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

x11docker --xpra --xc=yes --xauth=no --user=RETAIN \
  --clipboard \
  --name="$(basename "$1")" \
  --network=dev \
  -- \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --tmpfs /tmp:exec \
  -v "$SCRIPT_DIR/javaUserPrefs":/home/dev/.java/.userPrefs \
  -v intellij_config:/home/dev/.config/JetBrains \
  -v intellij_cache:/home/dev/.cache/JetBrains \
  -v "$1":/home/dev/project \
  -- \
  intellij:latest
