#!/bin/sh

set -eu

x11docker --nxagent --clipboard --no-auth --user=RETAIN --pw=none \
  --name="$(basename $1)" \
  -- \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --tmpfs /tmp:exec \
  --tmpfs /home/dev/.cache:exec,uid=1000,gid=1000 \
  --mount type=bind,src=$(pwd)/javaUserPrefs,dst=/home/dev/.java/.userPrefs \
  --mount type=bind,src="$HOME/$1",dst=/home/dev/project \
  --network=dev \
  -- \
  intellij:latest
