#!/bin/sh

docker run -it --rm --name code-server \
  -p 127.0.0.1:8443:8443 \
  --tmpfs /tmp:exec \
  --tmpfs /home/dev/.cache:uid=1000,gid=1000 \
  --mount type=bind,src="$(pwd)/settings.json",dst=/home/dev/.local/share/code-server/User/settings.json \
  --mount type=bind,src="$(pwd)/$1",dst=/home/dev/project \
  code-server-colin:latest
