#!/bin/sh

set -eu

docker run --rm -it \
  --cap-drop ALL --security-opt=no-new-privileges \
  --read-only \
  -u 1000:1000 \
  -v beets:/home/colin/.config/beets \
  -v "$HOME/proj/dockerfiles/beet/config.yaml":/home/colin/.config/beets/config.yaml:ro \
  -v "$HOME/Music":/home/colin/Music \
  -v "$HOME/apps/beet":/home/colin/workdir:ro \
  beet "$@"
