#!/bin/sh

set -eu

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

PROJ_DIR=$1
PROJ_NAME="$(basename $PROJ_DIR)"
CONTAINER_HOME=/home/dev

if [ -c /dev/ICEBREAKER ]; then
  ICEBREAKER_DEV=$(readlink -f /dev/ICEBREAKER)
  echo "Found /dev/ICEBREAKER linked to $ICEBREAKER_DEV"
  echo
  ICEBREAKER=--device=$ICEBREAKER_DEV
else
  ICEBREAKER=
fi

# shellcheck disable=SC2086
docker run --rm -it \
  --name="$PROJ_NAME" \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --network=none \
  --tmpfs /home/dev/.cache:uid=1000,gid=1000 \
  $ICEBREAKER \
  -v "$SCRIPT_DIR/fish_history":"$CONTAINER_HOME/.local/share/fish/fish_history" \
  -v "$PROJ_DIR":/home/dev/project \
  fpga-dev
