#!/bin/sh

set -eu

x11docker --user=RETAIN \
  --name=vlc \
  --pulseaudio=socket \
  -- \
  --cap-drop=ALL --security-opt=no-new-privileges \
  -u 1000:1000 \
  -v "$HOME/Videos":/home/colin/Videos:ro \
  -- \
  vlc "$@"
