#!/bin/sh

set -eu

x11docker --hostdisplay --backend=podman --user=RETAIN \
  --name=vlc \
  --pulseaudio=socket \
  --gpu \
  -- \
  --cap-drop=ALL --security-opt=no-new-privileges \
  -u 1000:1000 --userns=keep-id \
  -v "$HOME/Videos":/home/appuser/Videos:ro \
  -- \
  localhost/vlc "$@"
