#!/bin/sh

set -eu

# For hardware acceleration use
#   --xpra-xwayland
#   --device=/dev/dri
x11docker --nxagent --no-auth --user=RETAIN \
  --name=vlc \
  --pulseaudio=socket \
  -- \
  --cap-drop=ALL --security-opt=no-new-privileges \
  -v "$(pwd)":/home/appuser/workdir:ro \
  -v "$HOME/proj/dockerfiles/vlc/KEYDB.cfg":/home/appuser/.config/aacs/KEYDB.cfg:ro \
  --device=/dev/sr0 \
  -- \
  vlc "$@"
