#!/bin/sh

set -eu

x11docker --nxagent --no-auth --user=RETAIN \
  --name=kicad \
  -- \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --network=none \
  -u 1000:1000 \
  -v "$1":/home/appuser/workdir \
  -- \
  kicad "$@"
