#!/bin/sh

set -eu

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

docker run --rm --init \
  --name="$(basename "$1")" \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --tmpfs /tmp:exec \
  -v "$1":/home/colin/project \
  -p 127.0.0.1:5900:5900 \
  kicad
