#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

PORT=$1; shift
BOARD=$1; shift
PROJ_DIR=$1; shift
PROJ_NAME="$(basename "$PROJ_DIR")"
CONTAINER_HOME=/home/dev

SERIAL_DEVICE=
if [ -c /dev/ttyACM0 ]; then
  SERIAL_DEVICE=--device=/dev/ttyACM0
  echo "Found serial $SERIAL_DEVICE"
elif [ -c /dev/ttyUSB0 ]; then
  SERIAL_DEVICE=--device=/dev/ttyUSB0
  echo "Found serial $SERIAL_DEVICE"
fi

DEBUG_DEVICE=
DEBUGGERS=('JLINK' 'STLINK')
for D in "${DEBUGGERS[@]}"; do
  if [ -c "/dev/$D" ]; then
    DEV_FILE=$(readlink -f "/dev/$D")
    echo "Found /dev/$D at $DEV_FILE"
    DEBUG_DEVICE=--device=$DEV_FILE
    break
  fi
done

echo "code-server listening on port $PORT"

# shellcheck disable=SC2086
docker run --rm --init \
  --name="$PROJ_NAME" \
  --cap-drop=ALL --security-opt=no-new-privileges \
  -p 127.0.0.1:$PORT:8080 \
  $SERIAL_DEVICE \
  $DEBUG_DEVICE \
  --tmpfs /tmp:exec \
  --tmpfs /home/dev/.cache:exec,uid=1000,gid=1000 \
  -v "$SCRIPT_DIR/settings.json":"$CONTAINER_HOME/.local/share/code-server/User/settings.json" \
  -v "$SCRIPT_DIR/fish_history":"$CONTAINER_HOME/.local/share/fish/fish_history" \
  -v "$PROJ_DIR":/home/dev/Arduino \
  "arduino-$BOARD" \
  code-server --auth=none --bind-addr=0.0.0.0:8080
