#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
USER_ID=1000

cd "$SCRIPT_DIR"
touch history
setfacl -m u:100999:rw history

docker run --rm -it \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only --network=none \
  -u "$USER_ID:$USER_ID" \
  -v "$SCRIPT_DIR/history":'/home/colin/.local/share/numbat/history' \
  numbat "$@"
