#!/bin/sh

set -eu

COMMAND=$(basename $0)

docker run --rm -i \
  --cap-drop ALL --security-opt=no-new-privileges \
  --read-only \
  -u 1000:1000 \
  --tmpfs=/tmp \
  --tmpfs=/home/colin/.cache \
  -v "$(pwd)":/home/colin/workdir:ro \
  --entrypoint="$COMMAND" \
  pip-tools \
  "$@"
