#!/bin/sh

set -eu

x11docker --nxagent --no-auth --user=RETAIN \
  --name=handbrake \
  -- \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --network=none \
  -u 1000:1000 \
  --device=/dev/sr0 \
  -v "$HOME/proj/dockerfiles/vlc/KEYDB.cfg":/home/appuser/.config/aacs/KEYDB.cfg:ro \
  -v "$HOME/apps/handbrake":/home/appuser/workdir \
  -- \
  handbrake "$@"
