#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

OUTPUT_TITLE="Polly - $1"
OUTPUT_TMP="/tmp/$OUTPUT_TITLE.mp3"

cat - | docker run --rm -i \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only \
  -u 1000:1000 \
  --tmpfs=/tmp \
  --env-file="$SCRIPT_DIR/env" \
  polly "$OUTPUT_TITLE" \
  > "$OUTPUT_TMP"

clip-copy "$OUTPUT_TMP" "$OUTPUT_TITLE"
rm -f "$OUTPUT_TMP"
