#!/usr/bin/env bash

set -euo pipefail

OUTPUT_TITLE="$1"
OUTPUT_FILE="$OUTPUT_TITLE.mp3"
TASK_ID=''
TASK=''
TASK_STATUS=''
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

_aws() {
  docker run --rm -i \
    --cap-drop=ALL --security-opt=no-new-privileges \
    --read-only \
    -u 1000:1000 \
    -v "$SCRIPT_DIR/config":/aws-config:ro \
    -v "$(pwd)":/mnt \
    -e AWS_CONFIG_FILE=/aws-config \
    -w /mnt \
    amazon/aws-cli "$@"
}

startTask() {
  TEXT_FILE=polly-$(cat /dev/urandom | tr -cd '0-9' | head -c 8).txt
  cat - > "$TEXT_FILE"

  TASK=$(_aws polly start-speech-synthesis-task \
     --output-s3-bucket-name="$POLLY_BUCKET" \
     --output-format=mp3 \
     --voice-id=Joanna \
     --text="file://$TEXT_FILE")
  TASK_ID=$(echo "$TASK" | jq -r .SynthesisTask.TaskId)
  echo "Started TaskId: $TASK_ID"

  rm "$TEXT_FILE"
}

getTask() {
  TASK=$(_aws polly get-speech-synthesis-task --task-id="$TASK_ID")
}

getTaskStatus() {
  getTask
  TASK_STATUS=$(echo "$TASK" | jq -r .SynthesisTask.TaskStatus)
}

startTask
getTaskStatus

while [ "$TASK_STATUS" != 'completed' ]; do
  printf "Status: %s    \r" "$TASK_STATUS"
  getTaskStatus
  sleep 3
done

echo

HTTPS_URL=$(echo "$TASK" | jq -r .SynthesisTask.OutputUri)
S3_URL=s3://$(echo -n "$HTTPS_URL" | grep -o 'polly.*')
_aws s3 cp "$S3_URL" "$OUTPUT_FILE"
_aws s3 rm "$S3_URL"

clip-copy "$OUTPUT_FILE" "$OUTPUT_TITLE"
