#!/usr/bin/env bash
set -euo pipefail

USER_ID=$(( 10000 + RANDOM % 10000 ))

docker run --rm -i \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only \
  -u $USER_ID:$USER_ID \
  -p 127.0.0.1:8001:8001 \
  -v "$(pwd)":/mnt:ro \
  -w /mnt \
  datasette "$@"
