#!/bin/sh

set -eu

docker run --rm -i \
  --cap-drop ALL --security-opt=no-new-privileges \
  --read-only \
  -u 1000:1000 \
  -p 127.0.0.1:8001:8001 \
  -v "$(pwd)":/mnt:ro \
  -w /mnt \
  datasette "$@"
