#!/bin/sh

set -eu

x11docker --xc=no --nxagent --user=RETAIN \
  --name=freecad \
  -- \
  --cap-drop=ALL --security-opt=no-new-privileges \
  -u 1000:1000 \
  -v "$1":/home/appuser/workdir \
  -- \
  freecad
