#!/usr/bin/env bash

set -euo pipefail

if [[ -t 0 ]]; then
  T='-t'
else
  T=''
fi

if [[ -t 1 ]]; then
  COLOR=always
  STYLE=full
  PAGING=auto
else
  COLOR=never
  STYLE=plain
  PAGING=never
fi

# shellcheck disable=SC2086
docker run --rm -i $T \
  --cap-drop ALL --security-opt=no-new-privileges \
  --read-only --network=none \
  -u 1000:1000 \
  -v "$(pwd)":/mnt:ro \
  -w /mnt \
  bat --color="$COLOR" --paging="$PAGING" --style="$STYLE" "$@"
