#!/usr/bin/env bash

set -euo pipefail

if [[ -t 0 && -t 1 ]]; then
  IT='-it'
  COLOR='always'
else
  IT='-i'
  COLOR='never'
fi

PAGING="$COLOR"

docker run --rm "$IT" \
  --cap-drop ALL --security-opt=no-new-privileges \
  --read-only --network=none \
  -u 1000:1000 \
  -v "$(pwd)":/mnt:ro \
  -w /mnt \
  bat --color="$COLOR" --paging="$PAGING" "$@"
