#!/bin/sh

x11docker --nxagent --no-auth --user=RETAIN \
  -- \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --tmpfs /tmp:exec \
  --tmpfs /home/dev/.cache:uid=1000,gid=1000 \
  --mount type=bind,src="$(pwd)/settings.json",dst='/home/dev/.config/Code - OSS/User/settings.json' \
  --mount type=bind,src="$(pwd)/$1",dst=/home/dev/project \
  -- \
  vscode:latest
