#!/bin/sh

set -eu

x11docker --nxagent --clipboard --user=RETAIN \
  --name="$(basename $1)" \
  -- \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --security-opt seccomp=seccomp-electron.json \
  --tmpfs /tmp:exec \
  --tmpfs /home/dev/.cache:uid=1000,gid=1000 \
  -v "$(pwd)/settings.json":'/home/dev/.config/Code - OSS/User/settings.json' \
  -v "$1":/home/dev/project \
  --network=dev \
  -- \
  vscode:latest
