#!/bin/sh

set -eu

docker run --rm -it \
  --name=rtl_433 \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --network=none \
  -u 16980:16980 \
  --device="$(readlink -f /dev/RTLSDR)" \
  rtl_433 "$@"
