#!/bin/sh

set -eu

COMMAND=$(basename $0)

docker run --rm -it \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only --network=none \
  -u 1000:1000 \
  --tmpfs=/tmp \
  --tmpfs=/home/appuser/.config/calibre:uid=1000,gid=1000 \
  -v "$HOME/apps/calibre":/home/appuser/workdir \
  --entrypoint="$COMMAND" \
  calibre \
  "$@"
