#!/usr/bin/env bash
set -euo pipefail

docker run --rm -it \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only --network=none \
  -u 1000:1000 \
  -v "$(pwd)":/home/colin/workdir \
  duckdb "$@"
