#!/usr/bin/env bash
set -euo pipefail

USER_ID=$(( 10000 + RANDOM % 10000 ))

HISTORY_FILE="$HOME/proj/dockerfiles/units/history"

if [ ! -f "$HISTORY_FILE" ]; then
  echo '' > "$HISTORY_FILE"
  chmod 666 "$HISTORY_FILE"
fi

docker run --rm -it \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only --network=none \
  -u $USER_ID:$USER_ID \
  ipcalc "$@"
