#!/bin/sh

set -eu

COMMAND=$(basename $0)

docker run --rm -it \
  --cap-drop ALL --security-opt=no-new-privileges \
  --read-only --network=none \
  -u 801:801 \
  --mount type=bind,src="$(pwd)",dst=/home/appuser/workdir \
  --entrypoint="$COMMAND" \
  imagemagick \
  "$@"
