#!/bin/sh

set -eu

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

if [ -c /dev/STLINK ]; then
  STLINK=--device="$(readlink -f /dev/STLINK)"
else
  STLINK=
fi

# shellcheck disable=SC2086
x11docker --nxagent --clipboard --user=RETAIN \
  --name="$(basename "$1")" \
  -- \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --security-opt seccomp="$SCRIPT_DIR/../seccomp-electron.json" \
  $STLINK \
  --tmpfs /tmp:exec \
  --tmpfs /home/dev/.cache:uid=1000,gid=1000 \
  -v "$SCRIPT_DIR/settings.json":'/home/dev/.config/Code - OSS/User/settings.json' \
  -v "$SCRIPT_DIR/fish_history":/home/dev/.local/share/fish/fish_history \
  -v "$1":/home/dev/project \
  --network=dev \
  -- \
  arm:latest
