#!/bin/sh
set -eu

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

$SCRIPT_DIR/xdg-open-server &

x11docker --xc=yes --xpra --user=RETAIN \
  --name=obsidian \
  --clipboard \
  -- \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --security-opt seccomp="$SCRIPT_DIR/../seccomp-electron.json" \
  -v obsidian_config:/home/colin/.config/obsidian \
  -v "$HOME/files/notes":/home/colin/workdir \
  -v "/tmp/xdg-open-fifo":/home/colin/xdg-open-fifo \
  -- \
  obsidian:latest
