#!/bin/sh

set -eu

x11docker --nxagent --no-auth --user=RETAIN \
  --name=musescore \
  --pulseaudio=socket \
  -- \
  --cap-drop=ALL --security-opt=no-new-privileges \
  -u 1000:1000 \
  -v "$HOME/proj/musescore":/home/colin/Documents/MuseScore2/Scores \
  -- \
  musescore "$@"
