#!/usr/bin/env bash
set -euo pipefail

USER_ID=$(( 10000 + RANDOM % 10000 ))

docker run --rm -it \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only --network=none \
  -u $USER_ID:$USER_ID \
  -v "$HOME/proj/dockerfiles/cheat/conf.yml":/conf.yml:ro \
  -v "$HOME/proj/cheatsheets":/mnt:ro \
  -e CHEAT_CONFIG_PATH=/conf.yml \
  -w /mnt \
  cheat "$@"
