#!/bin/sh

set -eu

docker run --rm -it \
  --name=transmission \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only \
  -u 1000:1000 \
  --tmpfs /home/appuser/.config:uid=1000,gid=1000 \
  -v "$HOME/apps/transmission":/home/appuser/Downloads \
  -p 127.0.0.1:9091:9091 \
  transmission \
  transmission-daemon -f -p 9091 -a '*.*.*.*' "$@"
