#!/usr/bin/env bash

set -euo pipefail

SERIAL_DEVICE=
if [ -c /dev/ttyUSB0 ]; then
  SERIAL_DEVICE=--device=/dev/ttyUSB0
fi

# shellcheck disable=SC2086
docker run --rm -it \
  --cap-drop ALL --security-opt=no-new-privileges \
  --read-only \
  -u 1000:1000 \
  $SERIAL_DEVICE \
  -v "$(pwd)":/config \
  ghcr.io/esphome/esphome:stable \
  "$@"
