#!/bin/sh

set -eu

docker run --rm -i \
  --cap-drop ALL --security-opt=no-new-privileges \
  --read-only \
  -u 1000:1000 \
  --tmpfs=/home/colin/.cache \
  -v "$(pwd)":/home/colin/workdir:ro \
  uv \
  "$@"
  #--tmpfs=/tmp \
