#!/bin/sh

set -eu

COMMAND=$(basename $0)

docker run --rm -i \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only --network=none \
  -u 801:801 \
  --entrypoint="$COMMAND" \
  json2yaml \
  "$@"
