#!/usr/bin/env bash

set -euo pipefail

USER_ID=$(( 10000 + RANDOM % 10000 ))

if [ -t 1 ]; then
  SH_OPTS='-t'
else
  SH_OPTS=''
fi

# shellcheck disable=SC2086
docker run --rm $SH_OPTS \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --read-only --network=none \
  -u $USER_ID:$USER_ID \
  -v "$(pwd)":/mnt:ro \
  -w /mnt \
  fd "$@"
