#!/bin/sh

set -eu

COMMAND=$(basename "$0")

if [ -t 0 ]; then
  IT='-it'
else
  IT='-i'
fi

docker run --rm "$IT" \
  --cap-drop ALL --security-opt=no-new-privileges \
  --read-only --network=none \
  -u 1000:1000 \
  --mount type=bind,src="$(pwd)",dst=/home/colin/workdir \
  --entrypoint="$COMMAND" \
  ffmpeg \
  "$@"
