#!/bin/sh

set -eu

COMMAND="$1"
shift

docker run --rm -it \
  --cap-drop ALL --security-opt=no-new-privileges \
  --read-only --network=none \
  -u 801:801 \
  --mount type=bind,src="$(pwd)",dst=/home/appuser/workdir \
  --entrypoint="$COMMAND" \
  ffmpeg \
  "$@"
