#!/bin/sh

set -eu

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
CONTAINER_HOME=/home/colin

PORT=$1; shift
PROJ_DIR=$1; shift
PROJ_NAME="$(basename $PROJ_DIR)"

echo "Listening on host port $PORT"

docker run --rm --init \
  --name="$PROJ_NAME" \
  --cap-drop ALL --security-opt=no-new-privileges \
  --network=dev \
  -p 127.0.0.1:$PORT:8080 \
  --tmpfs /tmp:exec \
  --tmpfs /home/colin/.cache:exec,uid=1000,gid=1000 \
  -v "$SCRIPT_DIR/settings.json":"$CONTAINER_HOME/.local/share/code-server/User/settings.json" \
  -v "$SCRIPT_DIR/fish_history":"$CONTAINER_HOME/.local/share/fish/fish_history" \
  -v "$PROJ_DIR":/home/colin/project \
  "$@" \
  go-dev --auth=none --bind-addr=0.0.0.0:8080
