#!/bin/sh

set -eu

PORT="$1"

echo "Listening on localhost:$PORT on host"
echo

docker run --rm -d --init --name=tiddlywiki \
  --cap-drop=ALL --security-opt=no-new-privileges \
  --mount type=bind,src="$HOME/notes/tiddlywiki",dst=/home/appuser/tiddlywiki/tiddlers \
  -p "127.0.0.1:$PORT:8080" \
  tiddlywiki . --listen host=0.0.0.0
